"""baseline

Revision ID: 84f45ff4e8ed
Revises: 
Create Date: 2026-06-12 10:36:18.873027
"""
from alembic import op
import sqlalchemy as sa


revision = '84f45ff4e8ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###