"""add recording columns

Revision ID: ce2e64605874
Revises: 84f45ff4e8ed
Create Date: 2026-06-12 10:44:27.121105
"""
from alembic import op
import sqlalchemy as sa


revision = 'ce2e64605874'
down_revision = '84f45ff4e8ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_contacts', sa.Column('recording_url', sa.Text(), server_default='', nullable=False))
    op.add_column('campaign_contacts', sa.Column('recording_egress_id', sa.String(length=120), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_contacts', 'recording_egress_id')
    op.drop_column('campaign_contacts', 'recording_url')
    # ### end Alembic commands ###